sudo: required
services:
    - docker

before_install:
    - docker build -t robertosegura/travis-test -f Dockerfile.dev .

script:
    - docker run robertosegura/travis-test npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "travis-test"
    env: "TravisTest-env"
    bucket_name: "elasticbeanstalk-us-east-1-498650009943"
    bucket_path: "travis-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

