sudo: required
services:
    - docker

before_install:
    - docker build -t robertosegura/travis-test -f Dockerfile.dev .

script:
    - docker run robertosegura/travis-test npm run test -- --coverage

